# Generated by Django 5.0.6 on 2024-08-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics/'),
        ),
    ]
